FROM sunasteriskrnd/php:%%version%%-fpm-%%debian_suite%%

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update \
    && apt-get install -y git vim \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug pcov \
    && docker-php-ext-enable xdebug pcov

COPY docker-php-ext-disable /usr/local/bin
