FROM sunasteriskrnd/php:{{ version }}-nginx-{{ distro_release }}

ENV COMPOSER_VERSION={{ composer_version }}

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version="$COMPOSER_VERSION"

COPY docker-php-ext-disable /usr/local/bin
